#!/bin/bash

# ===== File compression =====
tarit(){
  [ -e "$1" ] || {
      echo "A file or folder is required to continue." >&2
      return 1
  }

  # Check if `tar` is installed
  command -v tar >/dev/null 2>&1 || {
      echo "Failed to find tar binary" >&2
      return 1
  }

  # Check if `pigz` is installed
  command -v pigz >/dev/null 2>&1 || {
      echo "Failed to find pigz binary" >&2
      return 1
  }

  tar -cf - "$1" | pigz > "$1.tar.gz"
}


untarit(){
  # Check that a .tar.gz file was passed
  [[ "$1" == *.tar.gz ]] || {
      echo "A .tar.gz file is required to continue." >&2
      return 1
  }

  # Check that an existing file was passed
  [ -e "$1" ] || {
      echo "Failed to find such file." >&2
      return 1
  }

  # Check if `tar` is installed
  command -v tar >/dev/null 2>&1 || {
      echo "Failed to find tar binary." >&2
      return 1
  }

  # Check if `pigz` is installed
  command -v pigz >/dev/null 2>&1 || {
      echo "Failed to find pigz binary." >&2
      return 1
  }

	tar -I pigz -xf "$1"
}


# ===== Vim =====
v() {
    command vim "$@"
    cd .
}


# ===== React =====
ro() {
    cd "$ROOT/app/routes" >/dev/null 2>&1 || \
    cd "$ROOT/src/routes" >/dev/null 2>&1 || \
    {
        echo "Expected one of the following folders:
    => src/routes | app/routes" >&2
    }
}

co(){
    cd "$ROOT/src/components" >/dev/null 2>&1 || \
    cd "$ROOT/app/components" >/dev/null 2>&1 || \
    {
        echo "Expected one of the following folders:
    => src/components | app/components" >&2
        return 1
    }
}

s() {
    cd "$ROOT/src" >/dev/null 2>&1 || \
    cd "$ROOT/app" >/dev/null 2>&1 || \
        echo "Expected one of the following folders:
    => src | app" >&2
        return 1
}


# ===== Git =====
git() {
    case "$1" in
        switch|checkout|commit)
            command git "$@" && cd "$PWD"
            ;;
        branch)
            command git "$@" | cat
            ;;
        *)
            command git "$@"
            ;;
    esac
}


# ===== Rust =====
re() {
	[[ -d "$ROOT/target/release" ]] && \
      cd "$ROOT/target/release"
}

de() {
	[[ -d "$ROOT/target/debug" ]] && \
      cd "$ROOT/target/debug"
}
